import React, { useState } from "react";
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  Image,
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
} from "react-native";
import {
  ADMIN_SECRET_ID,
  isAdminId,
  verifyDriverLogin,
  DriverRecord,
} from "../services/database";

interface LoginScreenProps {
  onLoginSuccess: (session: {
    role: "admin" | "driver";
    driver?: DriverRecord;
  }) => void;
}

export const LoginScreen: React.FC<LoginScreenProps> = ({ onLoginSuccess }) => {
  const [loginId, setLoginId] = useState("");
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const handleLogin = async () => {
    const trimmed = loginId.trim();
    if (!trimmed) {
      setErrorMessage("Please enter your Login ID.");
      return;
    }

    setLoading(true);
    setErrorMessage(null);

    try {
      // 1. Check Admin Login format: sithuminaadmin$
      if (isAdminId(trimmed)) {
        setLoading(false);
        onLoginSuccess({ role: "admin" });
        return;
      }

      // 2. Check Driver Login via Firestore Database
      const driver = await verifyDriverLogin(trimmed);
      if (driver) {
        setLoading(false);
        onLoginSuccess({ role: "driver", driver });
        return;
      }

      // If neither matches
      setLoading(false);
      setErrorMessage(
        "Invalid ID. Please enter the Admin ID or your registered Driver ID (e.g. ST-DRV-XXXX)."
      );
    } catch (err: any) {
      setLoading(false);
      setErrorMessage(
        err?.message || "Failed to connect to database. Please check connection."
      );
    }
  };

  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === "ios" ? "padding" : "height"}
      style={styles.container}
    >
      <ScrollView
        contentContainerStyle={styles.scrollContent}
        keyboardShouldPersistTaps="handled"
      >
        {/* Header Branding */}
        <View style={styles.header}>
          <View style={styles.logoCircle}>
            <Image
              source={require("../../assets/logo.png")}
              style={styles.logo}
              resizeMode="contain"
            />
          </View>
          <Text style={styles.brandTitle}>සිතුමිණ ට්‍රාන්ස්පෝට්</Text>
          <Text style={styles.brandSubtitle}>Sithumina Driver App</Text>
          <Text style={styles.badgeText}>Admins & Drivers Portal</Text>
        </View>

        {/* Login Card */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Sign In to App</Text>
          <Text style={styles.cardDesc}>
            Enter your assigned Driver ID or Admin access key to continue.
          </Text>

          <View style={styles.inputGroup}>
            <Text style={styles.label}>Login ID</Text>
            <TextInput
              style={styles.input}
              placeholder="e.g. ST-DRV-1234 or Admin Key"
              placeholderTextColor="#8C877A"
              value={loginId}
              onChangeText={(text) => {
                setLoginId(text);
                if (errorMessage) setErrorMessage(null);
              }}
              autoCapitalize="none"
              autoCorrect={false}
              editable={!loading}
            />
          </View>

          {errorMessage ? (
            <View style={styles.errorBox}>
              <Text style={styles.errorText}>⚠️ {errorMessage}</Text>
            </View>
          ) : null}

          <TouchableOpacity
            style={[styles.button, loading && styles.buttonDisabled]}
            onPress={handleLogin}
            disabled={loading}
            activeOpacity={0.85}
          >
            {loading ? (
              <ActivityIndicator color="#26231B" />
            ) : (
              <Text style={styles.buttonText}>Log In to System ➔</Text>
            )}
          </TouchableOpacity>

          {/* Helper Tips */}
          <View style={styles.helpBox}>
            <Text style={styles.helpTitle}>💡 Access Guidelines:</Text>
            <Text style={styles.helpItem}>
              • <Text style={styles.bold}>Admin Access:</Text> Use the master admin key{" "}
              <Text style={styles.codeText}>sithuminaadmin$</Text>
            </Text>
            <Text style={styles.helpItem}>
              • <Text style={styles.bold}>Driver Access:</Text> Use the unique ID generated by your dispatch manager (e.g.{" "}
              <Text style={styles.codeText}>ST-DRV-XXXX</Text>).
            </Text>
          </View>
        </View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F2EA",
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    padding: 20,
    paddingTop: 50,
    paddingBottom: 40,
  },
  header: {
    alignItems: "center",
    marginBottom: 28,
  },
  logoCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "#FFC20E",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  logo: {
    width: 65,
    height: 65,
  },
  brandTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: "#26231B",
    marginBottom: 2,
  },
  brandSubtitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#26231B",
    marginBottom: 8,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#26231B",
    backgroundColor: "#FFE08A",
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 12,
    overflow: "hidden",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 22,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#E7E2D0",
  },
  cardTitle: {
    fontSize: 19,
    fontWeight: "800",
    color: "#26231B",
    marginBottom: 6,
  },
  cardDesc: {
    fontSize: 13,
    color: "#6F6A5A",
    lineHeight: 18,
    marginBottom: 20,
  },
  inputGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 13,
    fontWeight: "700",
    color: "#26231B",
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#F8F7F2",
    borderWidth: 1.5,
    borderColor: "#DCD6C4",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    fontWeight: "600",
    color: "#26231B",
  },
  button: {
    backgroundColor: "#FFC20E",
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
    shadowColor: "#FFC20E",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 2,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    fontSize: 15,
    fontWeight: "800",
    color: "#26231B",
  },
  errorBox: {
    backgroundColor: "#FEE2E2",
    borderRadius: 10,
    padding: 10,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#FCA5A5",
  },
  errorText: {
    fontSize: 12.5,
    color: "#B91C1C",
    fontWeight: "600",
  },
  helpBox: {
    marginTop: 22,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#EFECE3",
  },
  helpTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#524E42",
    marginBottom: 6,
  },
  helpItem: {
    fontSize: 11.5,
    color: "#6F6A5A",
    lineHeight: 17,
    marginBottom: 4,
  },
  bold: {
    fontWeight: "700",
    color: "#26231B",
  },
  codeText: {
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
    backgroundColor: "#FFF6D6",
    color: "#26231B",
    fontWeight: "700",
  },
});
